# fly.toml app configuration file generated for filcdn-indexer on 2025-05-29T10:47:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'filcdn-bot-mainnet'
primary_region = 'fra'

[env]
  DELAY = 30_000
  RPC_URL = 'https://api.node.glif.io/'
  PDP_VERIFIER_ADDRESS = '0xBADd0B92C1c71d02E7d520f64c0876538fa2557F'
  FWSS_STATE_VIEW_ADDRESS = '0x9e4e6699d8F67dFc883d6b0A7344Bd56F7E80B46'
  SERVICE_PROVIDER_REGISTRY_ADDRESS = '0xf55dDbf63F1b55c3F1D4FA7e339a68AB7b64A5eB'
  CDN_HOSTNAME = 'filbeam.io'

[build]

[[vm]]
  size = 'shared-cpu-1x'
